name: Release Workflow
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Release version/name
        required: true
  
jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          cache: 'go-build'

      - name: Build
        run: make release

      